name: Deploy to Production

on:
  release:
    types: [published]

jobs:
  deploy-production:
    name: Deploy production
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Production
      enable-sentry: false
      docker-image: ghcr.io/AplinkosMinisterija/stalu-rezervavimas-web
