name: Deploy to Production

on:
  release:
    types: [published]

jobs:
  deploy-production:
    name: Deploy production
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Production
      enable-sentry: false
      docker-image: ghcr.io/AplinkosMinisterija/darbo-vietu-rezervavimas-web
      cache-from: type=registry,ref=ghcr.io/aplinkosministerija/darbo-vietu-rezervavimas-web:buildcache
      cache-to: type=registry,ref=ghcr.io/aplinkosministerija/darbo-vietu-rezervavimas-web:buildcache,mode=max,image-manifest=true,oci-mediatypes=true,ignore-error=true
